version: '3.8'

services:
  spark:
    build: .
    container_name: spark-power-manager
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - TARGET_SERVER_IP=192.168.1.100
      - TARGET_SERVER_MAC=00:11:22:33:44:55
      - TARGET_SERVER_SSH_PORT=22
      - TARGET_SERVER_HTTP_PORT=11434
      - PING_INTERVAL=5000
      - HEALTH_CHECK_INTERVAL=10000
      - PORT=3000
    volumes:
      - ./logs:/app/logs
      - /etc/localtime:/etc/localtime:ro
    networks:
      - spark-network
    # Required for network operations (ping, WoL)
    cap_add:
      - NET_RAW
      - NET_ADMIN
    # Use host network for Wake-on-LAN to work properly
    network_mode: host

networks:
  spark-network:
    driver: bridge
