services:
  spark:
    build: .
    container_name: spark-power-manager
    restart: unless-stopped
    ports:
      - "${PORT:-3000}:3000"
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      - TARGET_SERVER_IP=${TARGET_SERVER_IP}
      - TARGET_SERVER_MAC=${TARGET_SERVER_MAC}
      - TARGET_SERVER_SSH_PORT=${TARGET_SERVER_SSH_PORT:-22}
      - TARGET_SERVER_HTTP_PORT=${TARGET_SERVER_HTTP_PORT:-11434}
      - PING_INTERVAL=${PING_INTERVAL:-5000}
      - HEALTH_CHECK_INTERVAL=${HEALTH_CHECK_INTERVAL:-10000}
      - PORT=${PORT:-3000}
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - SSH_USERNAME=${SSH_USERNAME}
      - SSH_PRIVATE_KEY_PATH=${SSH_PRIVATE_KEY_PATH}
    volumes:
      - ./logs:/app/logs
      - /etc/localtime:/etc/localtime:ro
      # Mount SSH key if specified
      - "${SSH_PRIVATE_KEY_PATH:-/dev/null}:${SSH_PRIVATE_KEY_PATH:-/dev/null}:ro"
    # Required for network operations (ping, WoL)
    cap_add:
      - NET_RAW
      - NET_ADMIN
    # Use host network for Wake-on-LAN to work properly
    network_mode: host