services:
  spark:
    build: .
    container_name: spark-power-manager
    restart: unless-stopped
    # REVERTED: Go back to bridge mode so the web UI is accessible.
    ports:
      - "3000:3000"
    environment:
      # --- Core SPARK Settings ---
      - NODE_ENV=${NODE_ENV:-production}
      - TARGET_SERVER_IP=${TARGET_SERVER_IP}
      - TARGET_SERVER_MAC=${TARGET_SERVER_MAC}
      - SSH_USERNAME=${SSH_USERNAME}
      - TARGET_SERVER_SSH_PORT=${TARGET_SERVER_SSH_PORT:-22}
      - TARGET_SERVER_HTTP_PORT=${TARGET_SERVER_HTTP_PORT:-11434}
      - PORT=${PORT:-3000}
      - LOG_LEVEL=${LOG_LEVEL:-info}
      # --- GPU Auto-Sleep Settings (from .env) ---
      - AUTO_SLEEP_GPU_THRESHOLD=${AUTO_SLEEP_GPU_THRESHOLD:-5}
      - AUTO_SLEEP_IDLE_MINUTES=${AUTO_SLEEP_IDLE_MINUTES:-5}
    volumes:
      - ./logs:/app/logs
      - ./.ssh:/app/.ssh
      - /etc/localtime:/etc/localtime:ro
    command: >
      sh -c "
        chown -R nodejs:nodejs /app/.ssh &&
        chmod 700 /app/.ssh &&
        chmod 600 /app/.ssh/* &&
        node dist/server.js
      "
    cap_add:
      - NET_RAW
      - NET_ADMIN

networks:
  spark-network:
    driver: bridge