services:
  spark:
    build: 
      context: .
      target: production
    container_name: spark-power-manager
    restart: unless-stopped
    # Use host networking for Wake-on-LAN functionality
    network_mode: host
    privileged: true
    environment:
      # --- Core SPARK Settings ---
      - NODE_ENV=${NODE_ENV:-production}
      - TARGET_SERVER_IP=${TARGET_SERVER_IP}
      - TARGET_SERVER_MAC=${TARGET_SERVER_MAC}
      - SSH_USERNAME=${SSH_USERNAME}
      - TARGET_SERVER_SSH_PORT=${TARGET_SERVER_SSH_PORT:-22}
      - TARGET_SERVER_HTTP_PORT=${TARGET_SERVER_HTTP_PORT:-11434}
      - PORT=${PORT:-3000}
      - LOG_LEVEL=${LOG_LEVEL:-info}
      # --- Performance Monitoring Debug ---
      - ENABLE_PERFORMANCE_DEBUG=${ENABLE_PERFORMANCE_DEBUG:-false}
      # --- Auto-Sleep Settings ---
      - AUTO_SLEEP_ENABLED=${AUTO_SLEEP_ENABLED:-false}
      - AUTO_SLEEP_MINUTES=${AUTO_SLEEP_MINUTES:-15}
      - AUTO_SLEEP_MONITOR_GPU=${AUTO_SLEEP_MONITOR_GPU:-false}
      - AUTO_SLEEP_GPU_THRESHOLD=${AUTO_SLEEP_GPU_THRESHOLD:-5}
      - AUTO_SLEEP_IDLE_MINUTES=${AUTO_SLEEP_IDLE_MINUTES:-5}
    volumes:
      - ./logs:/app/logs
      - ./.ssh:/app/.ssh
      - /etc/localtime:/etc/localtime:ro
